default:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      threads: 4
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}" 
      user: "{{ env_var('SNOWFLAKE_USER') }}" 
      password: "{{ env_var('DBT_ENV_SECRET_SNOWFLAKE_PASS') }}" 
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}" 
      role: "{{ env_var('SNOWFLAKE_ROLE') }}" 
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}" 
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}" 
      client_session_keep_alive: True

    embucket:
      type: snowflake
      host: localhost
      port: 3000
      protocol: http
      account: "test"
      user: "test" 
      password: "test"
      role: "ACCOUNTADMIN"
      database: "embucket"
      warehouse: "COMPUTE_WH"
      schema: "public" 
      threads: 4
